# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin!@#, roles: [ 'ROLE_ADMIN' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody
#        demo_login:
#            pattern:  ^/demo/secured/login$
#            security: false
        login:
          pattern:  ^/admin/login$
          anonymous: ~

        # secures part of the application
        secured_area:
            pattern:    ^/admin
            form_login:
               # if true, forward the user to the login form instead of redirecting
                use_forward: true
                use_referer: true
                always_use_default_target_path: true
                default_target_path: admin
                check_path: user_login_check
                login_path: user_login
                # field names for the username and password fields
                username_parameter: _username
                password_parameter: _password
                # by default, the login form *must* be a POST, not a GET
                post_only: true
                remember_me: true
            remember_me:
                key: "w490fjweqij9qjegwq"
                lifetime: 86400 # 24h in seconds
                path: /admin
                domain: ~ # Defaults to the current domain from $_SERVER
            logout:
                path:   user_logout
                target: user_login
            anonymous: ~
            http_basic: ~
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }