homepage:
    path: /
    defaults: { _controller: SiteBundle:Site:index }
    options:
            expose: true
send:
    path: /send
    defaults: { _controller: SiteBundle:Site:send }
    options:
            expose: true
